### ISSUE TITLE
What is ReqPoolSize?

### ISSUE THREAD

**Issue by mrmuell23** [aimms/documentation#2]
Can you add details as to what this option does?

https://documentation.aimms.com/httpclient/api.html

**Comment by ArthurAIMMS** [comment]
Hi @mrmuell23 , thanks for your question. 

@JorisKoster could you help us here ?

**Comment by ArthurAIMMS** [comment]
Hi @mrmuell23 , we have updated the docs and explained what ReqPoolSize was meant for in the following paragraph:
https://documentation.aimms.com/httpclient/usage.html#linkconfigreqpoolsize

There was also a typo in the procedure name that we corrected:
https://documentation.aimms.com/httpclient/api.html#web-setConfig

Thanks a lot for your feedback!
