### ISSUE TITLE
Mention behavior of IncludeEmptyColumns      for AXLL library

### ISSUE THREAD

**Issue by mrmuell23** [aimms/documentation#3]
https://documentation.aimms.com/aimmsxllibrary/using.html#writing-data

useful to mention in the library that the include empty columns will look at the top parent set for the base index of the identifier.  Passing an index pointing to a subset in the WriteTable function, that index/parent set is ignore.  

This happened when I called writetable where the parent set I had made a subset of allintegers.

**Comment by ArthurAIMMS** [comment]
Hi @mrmuell23 , I just updated the docs thanks to your feedback. Thanks very much !
